### ISSUE TITLE
Single Player - highest difficulty stuck

### ISSUE THREAD

**Issue by ryancrunchi** [blizzhackers/kolbot#102]
Steps to reproduce :
1 - Have a profile in mode Single Player
2 - Entry Script D2BotLead.dbj
3 - Difficulty Highest
4 - Have your char access to Nightmare difficulty, but not Hell
D2BS seems to infinite loop in clicking Hell difficulty which is not available.

Advanced :
In d2bs `DWORD Profile::login(char** error)` function
```
    case 3:
        // highest available
        if (!clickControl(findControl(6, (const wchar_t*)NULL, -1, 264, 383, 272, 35)) &&
            !clickControl(findControl(6, (const wchar_t*)NULL, -1, 264, 340, 272, 35)) &&
            !clickControl(findControl(6, (const wchar_t*)NULL, -1, 264, 297, 272, 35)))
            errorMsg = "Failed to click ANY difficulty button?";
        break;
```
It tries to click the highest difficulty button with any Disabled state. But it should try to find the highest difficulty button not Disabled.

**Comment by jogohnwer** [comment]
why dont you just set the difficulty in the profile maker/editor to nightmare or highest possible level
the profile editor is the program you use to launch your characters.
double click the profile 
go down do difficulty (left column)
set to desired difficulty. (normal, nightmare, hell, or highest difficulty available)

**Comment by jogohnwer** [comment]
ok i did read you state 

> 4 - Have your char access to Nightmare difficulty, but not Hell
D2BS seems to infinite loop in clicking Hell difficulty which is not available.

my bad to me that says that your in nm mode and your bot is trying to click hell mode which is not available like only being nm difficulty and that the bot is trying to get into hell at character screen in diablo game.
your correct i read it wrong.
-where i assume now that you mean that hell isnt an option available in d2bot?
but just for fun why dont you try to edit character profile and choose hell as a difficulty rather then max difficulty available.
assuming that my last assumption was incorrect.
other 2 things i can think of are 
-remake the profile
-get a fresh copy of kolbot.
the last is defiantly a last resort. since editing pickits and the other things takes a while. 
i would wait for a more seasoned member that can read to assist you better.
sorry i couldn't help. good luck.

**Comment by ryancrunchi** [comment]
The bug is in `login()` method inside d2bs, not D2Bot#.
I have posted a hint on where the bug may comes :
`clickControl(findControl(6, (const wchar_t*)NULL, -1, 264, 383, 272, 35))`
this line try to click Hell button, even if it disabled (-1).

Maybe a quick fix would be
`clickControl(findControl(6, (const wchar_t*)NULL, 1, 264, 383, 272, 35)`
This will try to find Hell button enabled, which will return false and try next button (Nightmare etc...)
but I'm not sure as I don't work on d2bs.

**Comment by theBGuy** [comment]
This has been fixed
