### ISSUE TITLE
Way for MFHelper to not clear independently or so far away from leader?

### ISSUE THREAD

**Issue by notenoughdamage** [blizzhackers/kolbot#139]
Any way for the MFHelper to not clear independently or so far away from the leader? I'd prefer to keep the group closer together. They can get separated in big maps and aren't nearly as effective or safe. My workaround right now is to have the MFHelpers open all interactables, but the leader ignores them. I couldn't seem to find any sort of distance to edit in the script?

Thanks so much for anybody's input

**Comment by DarkHorseDre** [comment]
I think the problem is in the way the bots navigate rooms - killing bots takes time and takes them out of whack (so does going to town, dying etc)

You're asking for a significant rework in order to handle all situations which cause this - but I'd post on discord and see if anyone has already done something like this. https://discord.gg/2SdYnn5p

**Comment by mf022** [comment]
> Any way for the MFHelper to not clear independently or so far away from the leader? I'd prefer to keep the group closer together. They can get separated in big maps and aren't nearly as effective or safe.

this feature is more like the followers are working.
in the past I changed a bit [the default Follower.js](https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md/#silenced-follower), to react automatically, but I used that script only with manually played leader.
maybe some changes should be added, including the communication, in order to request tp from leader, or other things.
