### ISSUE TITLE
can make maphack and mulelog at the same time

### ISSUE THREAD

**Issue by marklma** [blizzhackers/kolbot#180]
such as when I login a mule,and kolbot can log the items in the inventory and cube,and update when I login next time,so that I can find item in the extact mule easily.

**Comment by mf022** [comment]
even using the D2BotMap starter script, according to <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/default.dbj#L41-L62> the ToolsThread.js is loaded, so these lines <https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/tools/ToolsThread.js#L445-L449> are working.
Anytime you can press Numpad 6 key, in order to get the mulling of that char.
