### ISSUE TITLE
New functionality to start the bot when already logged in

### ISSUE THREAD

**Issue by antalj724** [blizzhackers/kolbot#186]
Hi All,

It would be great to have the functionality to start the bot only after the user has logged in to the battlenet and is online.

Regards

**Comment by mf022** [comment]
In order to access a d2 server, first of all you should start the profile in D2Bot manager. The conditions to join a d2 server are set in the starter scripts ( *.dbj).
After that, depending upon the timers and info for creating/joining games, the bot will make actions in game on that d2 server or tcp/ip.
