### ISSUE TITLE
How to make a safe path?

### ISSUE THREAD

**Issue by Blackphoen1x** [blizzhackers/kolbot#238]
Any good algorithms based on the A* path from D2BS, or any methods to stay away from monsters when my character is running across an area?

**Comment by gtoilet** [comment]
a good starting point would be the wakka.js it has avoid monsters in area around player
it would atleast give you something to start modding to fit your needs

**Comment by Blackphoen1x** [comment]
> a good starting point would be the wakka.js it has avoid monsters in area around player
> it would atleast give you something to start modding to fit your needs

I don't think so... In wakka.js there's a leader clearing path for the followers, while I want my leader to avoid monsters when walking the path without killing monsters. For example, making a lvl 1 character to walk from Blood Moor to Catacombs Level 4 without killing any monsters.

**Comment by jaenster** [comment]
spidermonkeys javascript is surprisingly quick if you do low level operations, due to the fact it does a pretty dope JIT for low level operations.

What you can do (but this takes some memory) is to write an astar algorithm in javascript using the collision map and add your own flags. [https://github.com/jaenster/ts-astar/blob/master/src/typedArray.ts](i once written it in typescript), im sure you can alter it so it works for 1) the game and 2) transpiled in javascript.

The link i give you is for typed arrays (which are quicker), but you can use a more javascript approach too.
If you use the getPath function that d2bs exploses, there is a mode for [https://github.com/noah-/d2bs/blob/master/Map/Path/Reduction/JSPathReducer.h](javascript) path reducing too, but i have no idea how its used, and/or if its fully implemented. @noah- might know more about this

**Comment by Blackphoen1x** [comment]
> spidermonkeys javascript is surprisingly quick if you do low level operations, due to the fact it does a pretty dope JIT for low level operations.
> 
> What you can do (but this takes some memory) is to write an astar algorithm in javascript using the collision map and add your own flags. [once i written my own in typescript](https://github.com/jaenster/ts-astar/blob/master/src/typedArray.ts) im sure you can alter it so it works for 1) the game and 2) transpiled in javascript.
> 
> The link i give you is for typed arrays (which are quicker), but you can use a more javascript approach too.
> If you use the getPath function that d2bs exploses, there is a mode for [javascript](https://github.com/noah-/d2bs/blob/master/Map/Path/Reduction/JSPathReducer.h) path reducing too, but i have no idea how its used, and/or if its fully implemented. @noah- might know more about this.
> 
> edit; i messed up the link tags

Yes, it makes sense. Thank you.
