### ISSUE TITLE
How to Multi-task

### ISSUE THREAD

**Issue by XternalFactor** [blizzhackers/kolbot#283]
I made my own very basic and simple Lower Kurast code.

However I am wanting to incorporate opening chests WHILST clearing mob bosses, while clearing the mob bosses is a main priority

So for example;
SaidChar attacks mob, kills mob, opens nearby chest, continues to move to next location to kill mob and/or open chest, moves on until area cleared.

here is current code:

function LowerKurast() {
	
	var ClearMobs = Config.ClearMobs,
		ChestPoppin = Config.Chestpoppin;
	
	Town.doChores();
	Pather.useWaypoint(79);
	Precast.doPrecast(true);
	
	if (Config.ChestPoppin && me.area == 79) {
		Misc.openChestsInArea();
	}
	
	if (Config.ClearMobs) {
		Attack.clearLevel(Config.ClearType);
	}
	
	return true;
}

**Comment by Blackphoen1x** [comment]
You just need to turn on this:
`Config.OpenChests = true;`
This will open all types of chests while pathing. You can check Pather.js>NodeAction>popChests for detail reason.
If you want to limit  the type of chests, you need to override Misc.openChests function.

**Comment by XternalFactor** [comment]
> You just need to turn on this:
> `Config.OpenChests = true;`
> This will open all types of chests while pathing. You can check Pather.js>NodeAction>popChests for detail reason.
> If you want to limit the type of chests, you need to override Misc.openChests function.

No, this is a very basic and generalized response.

For the rest of the class, all other newbs that think they’re coders and want to offer basic generalized answers like this guy, you will be dismissed as well as your input is not needed..

thank you, still looking for a resolution.

**Comment by Blackphoen1x** [comment]
lol, I actually don't understand where ur ego comes and ur definately not a coder since u cannot even solve such a easy issue :)
In Attack.clearLevel function, character will get all rooms in an area, go to the center coord of the nearest room then clear monsters in a range of 40 until all the coords are achieved. 
In Misc.openChestsInArea, character will get all presetUnit chests in an area, go to the nearest chest and open all the chests in a range of 20 until all the coords are achieved.
Solution is clear then, put all the room coords and presetUnit chests coords in a same list, go to the nearest coord and do ur task until all the coords are achieved.
Another solution is to just check and open chests nearby every time your character make a move(Pather.moveTo), this is what I said before because in Pather.moveTo function, if you set  `Config.OpenChests = true; ` character will do NodeAction.popChests, check it in Pather.js(around line 55) and you will see Misc.openChests(20);
Well, I admit it the second solution is basic and generalized  since it may miss some chests although deafult teleport range is 40 and openChests range is 20. 
Multi-thread API provided by D2BS can also be used here, for example, `load("checkChests.js")`, then in checkChests.js>main function check chest units nearby every 1 second, each time you get a chest unit nearby, pause default.dbj(just refer this.togglePause function in Toolsthread.js) and open chests with checkChests.js thread. This is not recommened coz it takes more CPU occupation.
Since you can write your own code and image me as a newb, I don't think you need detail codes here :)

**Comment by XternalFactor** [comment]
This is what i was looking for to begin with... not some "just change this --> Config.OpenChests = true;"

The problem with just that code itself is that it is generalized in the WHOLE CONFIG, and NOT JUST THAT AREA.

I get that but i dont want it to open chests in all areas, just this particular area in a given run.

I did manage to put the "openchestsinarea" in the pit script and it works because when i run the pit before it never opened the chest in pitlvl2.

However pitlvl2 is a relatively small area like you said, with default teleport range being 40.

I will work on this code and just leave it for myself then.  Again, thank you for your input which helps.  but the "change this Config.OpenChests = true;" was an extremely basic response as that is not what i was lookgn for.

**Comment by XternalFactor** [comment]
To add to that about pitlvl2 also is that there is only 1 chest to worry about..

What i am trying to accomplish here is 
wherever "pathermoveto --> kill monster, open nearby chests after the mob is clear. then move to the next area of 79 to kill the next mob, then open chests in that area..

Make sense?

**Comment by jaenster** [comment]
Sorry for the late reply, I have to be honest i didnt read all your replies fully, but it feels like your trying to achive async behaviour in an engine that doesnt not have it.

I did try to achive this with background workers, which is basiclly a trick to override the delay functionality that d2bs exposes but isnt part of the javascript spec, while waiting it is executing background things. Since 97% of the time the bot runs, its waiting, its a perfect spot to put it in;

https://github.com/blizzhackers/kolbot/blob/dbb028623b144728e9bd47cf420b5006524f4d98/d2bs/kolbot/libs/modules/SimpleParty.js#L74

Here is a party script that runs within the same scope and thread as the main thread, giving it the ability to do something while running. Be careful with recursive issues
