### ISSUE TITLE
BO BUG

### ISSUE THREAD

**Issue by fabznn** [blizzhackers/kolbot#324]
Please man repair this Bo Script, so Barb wait for all Getters and then BO.
He always BO as he gets into the bo place, and so not all chars get bo and then they just stand there and do nothing.

**Comment by aim2kill** [comment]
Ok now this is the right place did u config this part to wait for all players before giving bo?
Config.BattleOrders.Getters = [];

**Comment by fabznn** [comment]
yes i did that all like this:
Config.BattleOrders.Getters = [“nameofcharacter1”, “nameofcharacter2”, “nameofcharacter3”];

but somehow it doesn't work. Barb goes into area and instantly starts BOing, he doesn't wait for the others.

**Comment by aim2kill** [comment]
Can u post the whole barb Bo setting
Can you post what u have for barb and 
Scripts.BattleOrders = false;
		Config.BattleOrders.Mode = 0;
		Config.BattleOrders.Idle = false; 
		Config.BattleOrders.Getters = [];
		Config.BattleOrders.QuitOnFailure = false; 
		Config.BattleOrders.SkipIfTardy = true;
		Config.BattleOrders.Wait = 10;

**Comment by fabznn** [comment]
Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Idle = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = ["name1", "name2", "name3", "name4", "name5"]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.
		Config.BattleOrders.QuitOnFailure = false; // Quit the game if BO fails
		Config.BattleOrders.SkipIfTardy = true; // Proceed with scripts if other players already moved on from BO spot
		Config.BattleOrders.Wait = 10; // Duration to wait for players to join game in seconds (default: 10)

**Comment by theBGuy** [comment]
https://github.com/blizzhackers/kolbot/tree/AttackCleanup

Run this branch, I've had some bots going for the past couple hours and so far haven't missed a bo. Please let me know if you run into any isses

**Comment by fabznn** [comment]
Thank you for your help, but now he is waiting 2 minutes for "other players" although all chars are ingame and in zone. how can i delete that timer? i think then it will work properly.

**Comment by fabznn** [comment]
ok i found it out by myself: the problem was the line where it converts the character names to lowercase. i commented this out and now it is working.

**Comment by fabznn** [comment]
Ok it seems sometimes he is waiting those 2 minutes again after some successful runs. why is that?

**Comment by theBGuy** [comment]
The steps are as follows
- bo-barb joins the game and goes to cata
- he'll wait unitl at least one person has shown up who is in the list of bo-getters.
- after that it initializes a 30second wait while checking for more players that breaks if the amount of players is equal to to be bo getter list length
- he'll then bo, and delay for 5 seconds to wait for the bo-ers to leave
- it then returns from the bo function and checks the amount of bots just bo-ed to the bo getter list length. If it was equal then it breaks and ends the script
- otherwise it starts a two-minute counter to see if anyone else on the list shows up and if not it exits as to not waste any more time

If he is waiting the two-minutes I would guess that some of your bo-ers were a little late but not late enough to actually miss the bo (You didn't mention if they failed to get bo-ed so I'm assuming they didn't). But they were late enough to not get counted when the list was build of near units. I can experiment a bit more when the different delays, but I don't want it to be too long which would mean having to increase the default wait time of the bo-ers

**Comment by fabznn** [comment]
thank you very much for your help. @theBGuy
