### ISSUE TITLE
D2BS is not responding... starting profile

### ISSUE THREAD

**Issue by Pichnouf** [blizzhackers/kolbot#338]
Hi, 
Win10 x64, D2 Lod 1.14D
When I start a D2Bot profile with a map script, the game starts; then crash after 10 secs.
Console message: D2BS is not responding... starting profile
I reinstalled C++ and .NET Framework, both D2Lod and D2BS folders are in (C:) root, all is running Win7 compatibility mode and as admin, i tried different versions of Kolbot project (LastStable, Blizzhackers) via Tortoise SVN or .zip DL. 
Game works fine both full screen and -w mode, D2BotSharp have firewall authorization. 
Every try is a no-go; D2Bot fails to inject and crashes.
Help needed.

**Comment by manphiz** [comment]
Did you make sure that the .NET Framework you installed was 32-bit?

**Comment by theBGuy** [comment]
https://github.com/blizzhackers/kolbot#install-dependencies---do-this-first
Most likely didn't install the correct version. Make sure c++ 2010 x86 is installed not the x64

**Comment by manphiz** [comment]
This is most definitely not because of the wrong msvc runtime library version because I actually made that mistake when I first set up D2BS with the x64 version and it couldn't even launched the bots at all, and after installing the x86 version the bots could start normally.

That being said, I actually made some progress here as I discovered that in D2Bot there is "Response time" setting in "Settings", and increasing it to 30 seconds gave the bots sufficient time to TP most of the time and hence D2BS will not crash any more.  I guess the response check in D2Bot use the same error message which may be why they gave the same error messages.

The remaining issue is still related to the long TP time that because of the delay, the town check sometimes failed as it would check whether it was in town even if the TP didn't finish, and it will quit.  I'm trying to tweak [1] or [2] with longer timeout but it doesn't work reliably yet.

Anyway, as the first issue has been resolved mostly, I'll probably open a new issue with the 2nd part.

Thanks!  And happy new year!

[1] https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Town.js#L2346
[2] https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/common/Town.js#L2350
