### ISSUE TITLE
Issue with BoBarbHelper

### ISSUE THREAD

**Issue by Lorincz** [blizzhackers/kolbot#42]
Hey,

First of all, thanks for creating this script. This is exactly what I needed :)

For the barb, it works perfectly, it is going down to Catacombs and gives Bo. My problem is with other characters. As an example if I include this script for a Paladin, ass soon as it starts the script the app unexpectedly crash.

Scripts.BoBarbHelper = true; // specific HC script with BoBarb on the Bo area during whole game
		Config.BoBarbHelper.Mode = 1; // 0 = give BO, 1 = get BO, -1  = disabled
		Config.BoBarbHelper.Wp = 35; // 35 = Catacombs level 2
		Config.BoBarbHelper.BoDuration = 400; // the barbarian char duration of BO skill in seconds (it can be the lower value between BC-BO-Shout)

Could you help me with this?

Regards,
Istvan

**Comment by mf022** [comment]
any error messages related to that crash in d2bs.log, or ...\kolbot\logs\ScriptErrorLog.txt ?

**Comment by Lorincz** [comment]
I will check it later today and share my config. Thanks for the quick response :)

**Comment by mf022** [comment]
I reverted a part of the changes related to BoGetting, because of issues of interrupting running area script when movement to Bo area was done.

the previous method for getting bo was added in the guide https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md/#modded-battleordersjs

**Comment by ChefKeeper** [comment]
This feature is really nice, any way to repair it ?
