### ISSUE TITLE
Where to add requests?

### ISSUE THREAD

**Issue by xWickedx420** [blizzhackers/kolbot#86]
Anyway we can incorporate a loot filter? Change HR's Colors or other things?

**Comment by moodew** [comment]
Not sure I understand what you mean, you are aware of pickit?

**Comment by xWickedx420** [comment]
I mean like, the ability to filter out basic items, and the ability to change the color of certain items like Runes, etc. 
Not all of us bot, some of us use it for maphack and a loader. without the pickit. I don't know how hard it would be to add what i describedm, or if its possible?

Thanks!

**Comment by gtoilet** [comment]
your talking like path of exile loot filter i dont know if its possiable

**Comment by Fa-b** [comment]
As you have mentioned yourself, this request is not really related to the kolbot scripts. If I understand correctly, you are trying to change ingame behaviour to highlight user defined items. Afaik this is not intended by D2BS and so there is no way to achieve what you want by just writing/changing some javascript here.

I'm closing this since it seems this is not the right place for it, feel free to reopen with more explanation if I got it wrong.
